# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09b57f1c62bde70b6a560552c215619681fca2f481e06949ea7644b592d9d02abf6c10a45fa891cd9555fe73f9df78e289214c2d7cefa23da2491f4ffdbc5513

test:
  secret_key_base: 83e371275e0396ba014ccf4f2df881fc9d3c6c835323c4494a522c140d569bd90455d993e7c252858b0a3d9915ebbb85b64b8de81d0f5cddd6f68cfaa5651807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
